WITH S AS (
    SELECT A.AUTHOR_ID
        , A.CATEGORY
        , SUM(B.SALES * A.PRICE) AS SALES
    FROM BOOK A
    JOIN BOOK_SALES B
    ON A.BOOK_ID = B.BOOK_ID
    WHERE B.SALES_DATE BETWEEN DATE '2022-01-01' AND DATE '2022-01-31'
    GROUP BY A.AUTHOR_ID, A.CATEGORY
)

SELECT S.AUTHOR_ID
    , C.AUTHOR_NAME
    , S.CATEGORY
    , S.SALES
FROM S
JOIN AUTHOR  C
ON S.AUTHOR_ID = C.AUTHOR_ID
ORDER BY S.AUTHOR_ID ASC, S.CATEGORY DESC;