-- 상품코드 별 매출액(판매가 * 판매량) 합계를 출력
-- 매출액 기준 내림차순, 매출액이 같다면 상품코드 기준 오름차순 
SELECT A.PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
FROM PRODUCT A
JOIN OFFLINE_SALE  B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES DESC, A.PRODUCT_CODE ASC;