-- 년, 월, 성별 별로 상품을 구매한 회원수를 집계 (성별 정보가 없는 경우 제외)
-- 년, 월, 성별을 기준으로 오름차순
SELECT TO_NUMBER(TO_CHAR(B.SALES_DATE, 'YYYY')) AS YEAR
    , TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM')) AS MONTH 
    , A.GENDER 
    , COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A
JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY TO_NUMBER(TO_CHAR(B.SALES_DATE, 'YYYY')), TO_NUMBER(TO_CHAR(B.SALES_DATE, 'MM')), A.GENDER
ORDER BY YEAR, MONTH, A.GENDER
