-- 대여 시작일이 2022년 9월에 속하는 대여 기록에 대해서 
-- 대여 기간이 30일 이상이면 '장기 대여' 그렇지 않으면 '단기 대여' 로 표시(RENT_TYPE)
SELECT HISTORY_ID
    , CAR_ID
    , TO_CHAR(START_DATE, 'YYYY-MM-DD')
    , TO_CHAR(END_DATE, 'YYYY-MM-DD')
    , CASE WHEN END_DATE - START_DATE + 1 >= 30
      THEN '장기 대여' ELSE '단기 대여' END RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN DATE '2022-09-01' AND DATE '2022-09-30'
ORDER BY HISTORY_ID DESC;