SELECT A.CAR_ID
    , CASE
        WHEN A.CNT > 0 
        THEN '대여중'
        ELSE '대여 가능'
        END AS AVAILABILITY
FROM (
    SELECT CAR_ID, MAX(CASE
                WHEN DATE '2022-10-16' BETWEEN START_DATE AND END_DATE
                THEN 1 ELSE 0 END 
              ) CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    GROUP BY CAR_ID
) A
ORDER BY A.CAR_ID DESC;