-- 아직 입양을 못 간 동물 중, 가장 오래 보호소에 있었던 동물 3마리의 이름과 보호 시작일
-- 보호 시작일 순
SELECT T.NAME, T.DATETIME
FROM (
    SELECT A.NAME, A.DATETIME
    FROM ANIMAL_INS A
    LEFT JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE B.DATETIME IS NULL
    ORDER BY A.DATETIME
) T
WHERE ROWNUM <= 3;