-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출(가격*주문량) 조회
-- 총매출 기준 내림차순, 식품 ID 기준 오름차순 
SELECT A.PRODUCT_ID
    , A.PRODUCT_NAME
    , A.PRICE * B.TOTAL_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN (
    SELECT PRODUCT_ID
        , SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN DATE '2022-05-01' AND DATE '2022-05-31'
    GROUP BY PRODUCT_ID
) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC;