SELECT A.HISTORY_ID
    , B.DAILY_FEE * ((100 - NVL(C.DISCOUNT_RATE, 0)) / 100) * A.DURATION AS FEE
FROM (
  SELECT HISTORY_ID, CAR_ID, DURATION
         , CASE WHEN DURATION >= 90 THEN '90일 이상'
                WHEN DURATION >= 30 AND DURATION < 90 THEN '30일 이상'
                WHEN DURATION >= 7 AND DURATION < 30 THEN '7일 이상'
            END DURATION_TYPE
    FROM (
        SELECT HISTORY_ID, CAR_ID
            , END_DATE - START_DATE + 1 AS DURATION
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    )
) A
JOIN CAR_RENTAL_COMPANY_CAR B
  ON A.CAR_ID = B.CAR_ID 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
  ON B.CAR_TYPE = C.CAR_TYPE AND A.DURATION_TYPE = C.DURATION_TYPE
WHERE B.CAR_TYPE = '트럭'
ORDER BY FEE DESC, A.HISTORY_ID DESC;