-- 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량을 더한 값이 큰 순서대로 
-- 상위 3개의 맛을 조회
SELECT FLAVOR
FROM
(
    SELECT A.FLAVOR
    FROM (
        SELECT FLAVOR, SHIPMENT_ID
            , SUM(TOTAL_ORDER) OVER(PARTITION BY FLAVOR) TOTAL_ORDER
        FROM FIRST_HALF 
    ) A
    JOIN (
        SELECT FLAVOR, SHIPMENT_ID
            , SUM(TOTAL_ORDER) OVER(PARTITION BY FLAVOR) TOTAL_ORDER
        FROM JULY
    ) B 
    ON A.SHIPMENT_ID = B.SHIPMENT_ID AND A.FLAVOR = B.FLAVOR
    ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
)
WHERE ROWNUM <= 3;