-- 0시부터 23시까지, 각 시간대별로 입양이 몇 건이나 발생했는지 
-- 시간대 순으로 정렬
SELECT B.HOUR
    , COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A
RIGHT JOIN (
    SELECT (LEVEL - 1) AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <= 24
) B
ON TO_NUMBER(TO_CHAR(A.DATETIME, 'HH24')) = B.HOUR
GROUP BY B.HOUR
ORDER BY B.HOUR;