SELECT  TO_NUMBER(TO_CHAR(START_DATE, 'MM')) AS MONTH
        , CAR_ID
        , COUNT(*) AS RECORDS
FROM (
    SELECT  H.*
            , COUNT(*) OVER(PARTITION BY CAR_ID) AS TOTAL_CNT
    FROM   CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE START_DATE >= TO_DATE('2022-08', 'YYYY-MM') 
      AND START_DATE < TO_DATE('2022-11', 'YYYY-MM')
)
WHERE TOTAL_CNT >= 5
GROUP BY TO_CHAR(START_DATE, 'MM'), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC