-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK A
JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID 
AND B.SALES_DATE BETWEEN DATE '2022-01-01' AND DATE '2022-01-31'
GROUP BY CATEGORY
ORDER BY CATEGORY;