-- 만원 단위의 가격대 별로 상품 개수를 출력
-- 컬럼명은 PRICE_GROUP, PRODUCTS
-- 가격대: 각 구간의 최소금액(10,000원 이상 ~ 20,000 미만인 구간인 경우 10,000)으로 표시
SELECT TRUNC(PRICE, -4) AS PRICE_GROUP
    , COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY TRUNC(PRICE, -4)
ORDER BY PRICE_GROUP